### ISSUE TITLE
Misleading description

### ISSUE THREAD

**Issue by Unrud** [ektor5/init-headphone#1]
Hi,
the tool has nothing to do with VIA VT1802.
The W230SS has an separate headphone amplifier (maybe made by http://www.savitech-ic.com) that is downstream from the audio codec.

**Comment by ektor5** [comment]
Oh, you're right, I'm going to change that! BTW, the issue involve only the Clevo W230SS?
Thanks for the notification

**Comment by ektor5** [comment]
I changed the description and added you to the credits, and thanks again for the script you made!
Cheers

**Comment by Unrud** [comment]
According to their [service manuals](https://biosmods.wordpress.com/service-manuals/) the models W350SS, W355SS and W370SS have the same amplifier.
But I can't find anyone complaining about issues with this models. Maybe they have fixed the firmware or nobody is using them with Linux.

**Comment by ektor5** [comment]
Probably. I think eventually someone can figure out the solution either posting on the bug thread or reading this.
